### ISSUE TITLE
Custom DNS resolver

### ISSUE THREAD

**Issue by jesusprubio** [jesusprubio/up#31]

**Comment by mohitsethia** [comment]
Hi @jesusprubio , I would like to contribute to this if you could help me a bit by adding more description to the issue, and what needs to be done.

**Comment by jesusprubio** [comment]
Hi @mohitsethia , I appreciate it.

The idea is to use a custom DNS resolver [here](https://github.com/jesusprubio/up/blob/520cd9e9fc0c35e2b1be6f70106bf6ed222bb54a/pkg/protocols.go#L79). Similar to this example: https://stackoverflow.com/a/59889883.

We also need to add a new option in the CLI [here](https://github.com/jesusprubio/up/blob/520cd9e9fc0c35e2b1be6f70106bf6ed222bb54a/internal/options.go#L33). For example: `flag.StringVar(&opts.DNSResolver, "r", "", "DNS resolution server")`

By default, the one defined in the operating system should be used (like now).

**Comment by mohitsethia** [comment]
Thanks for sharing. I am really sorry to bother you.
So, there are 2 ways of doing it, adding another protocol with "customDNSProbe" key and use it based on the input received from options DNSResolver flag while getting `GetProtocolByIDWithCustomDNSResolver(id, dnsResolver) *pkg.Protocol` that returns the customDNSProbe(domain, timeout) and implements the custom resolver.
Or pass the opts struct to the Probe methods to be able to check if we have custom dns resolver not empty then proceed with the custom dns resolver otherwise the default one.
How would you suggest passing this info that we have a custom DNS resolver to the dnsProbe function?

**Comment by mohitsethia** [comment]
@jesusprubio  Just an sample of how we can do additionally by adding WithDNSResolver method over Protocol. [Commit](https://github.com/jesusprubio/up/commit/12c4734fae33e4d66ba4abfa33c9003547e84586). If this look fine to you, maybe I can add test cases and raise the PR.

**Comment by jesusprubio** [comment]
My fault, probably this is not the best `good first issue`. It implies more changes than I initially thought.

**Comment by mohitsethia** [comment]
There is another way of doing it by passing opts ...string/Options to the probe methods. By adding another probe method for customDNSProbe. Both of these ways are also simple.

**Comment by mohitsethia** [comment]
Hey, sorry to bother you. I have added another way of doing this [change](https://github.com/jesusprubio/up/compare/main...mohitsethia:up:add-custom-dns-resolver?expand=1). To keep it consistent I have added the other Probes (http & tcp) under receiver method too. How does this look? It's less complicated.

**Comment by mohitsethia** [comment]
Hey @jesusprubio , sorry to bother you. I have added another way of doing this [change](https://github.com/jesusprubio/up/compare/main...mohitsethia:up:add-custom-dns-resolver?expand=1). To keep it consistent I have added the other Probes (http & tcp) under receiver method too. How does this look? It's less complicated.
